app/config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('members/', include('members.urls')),
]
# MEDIA_URL로 시작하는 URL은 static()내의 serve() 함수를 통해 처리
# MEDIA_ROOT기준으로 파일을 검색함
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
from django.urls import path

from members import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

app/posts/urls.py
from django.urls import path
from . import views

# 이 url모듈의 app_name에 'posts'를 사용
# reverse또는 템플릿의 {% url %}태그에서 사용
app_name = 'posts'

urlpatterns = [
    # posts.urls 내의 패턴들은, prefix 가 '/posts/'임
    path('', views.post_list, name='post-list'),
    path('create/', views.post_create, name='post-create')
]

app/members/models.py
# from django.db import models
#
#
# class User(models.Model):
#     username = models.CharField(
#         '아이디',
#         max_length=50,
#         unique=True,
#     )
#     img_profile = models.ImageField(
#         '프로필 이미지',
#         upload_to='user',
#         blank=True,
#     )
#     name = models.CharField(
#         '이름',
#         max_length=30, blank=True,
#     )
#     site = models.URLField(
#         '사이트',
#         max_length=150, blank=True,
#     )
#     introduce = models.TextField('소개', blank=True,)
#
#     def __str__(self):
#         return self.username
#
#     class Meta:
#         verbose_name = '사용자'
#         verbose_name_plural = '사용자 목록'

app/posts/models.py
from django.conf import settings
from django.db import models


class Post(models.Model):
    author = models.ForeignKey(
        # <AppName>.<ModelName>
        # 'members.User',
        # django 가 기본적으로 제공하는 User 클래스
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='작성자',
    )
    photo = models.ImageField(
        '사진',
        upload_to='post',
    )
    # auto_now_add : 객체가 처음 생성될떄의 시간 저장
    # auto_now : 객체의 save()가 호출될 때 마다 시간 저
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '포스트'
        verbose_name_plural = f'{verbose_name} 목록'
        ordering = ['-pk']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='포스트',
    )
    author = models.ForeignKey(
        # 'members.User',
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='작성자',
    )
    content = models.TextField()
    tags = models.ManyToManyField(
        'HashTag',
        blank=True,
        verbose_name='해시태그 목록',
    )

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = f'{verbose_name} 목록'


class HashTag(models.Model):
    name = models.CharField('태그명', max_length=100)

    class Meta:
        verbose_name = '해시태그'
        verbose_name_plural = f'{verbose_name} 목록'

    def __str__(self):
        return self.name

app/members/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )


class SignupForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

app/posts/forms.py
from django import forms


class PostCreateForm(forms.Form):
    photo = forms.ImageField(
        # 이 필드는 파일입력 위젯을 사용
        widget=forms.FileInput(
            # HTML위젯의 속성 설정
            # form-control-file클래스를 사용
            attrs={
                'class': 'form-control-file',
            }
        )
    )
    comment = forms.CharField(
        # 반드시 채워져 있을 필요는 없음
        required=False,
        # HTML 랜더링 위젯으로 Textarea 를 사용
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        ),
    )

app/config/views.py
import os

from django.conf import settings
from django.http import HttpResponse, FileResponse


# def media_serve(request, path):
    # 1. /media/로 시작하는 모든 URL은 이 view를 통해 처리
    # 2. /media/<뒤쪽 경로>/ 에서
    #   <뒤쪽 경로>부분을 path변수에 할당


    # 3. settings에 있는 MEDIA_ROOT를 기준으로
    #   <뒤쪽 경로>에 해당하는 파일의 경로를 file_path변수에 할당
    #       MEDIA_ROOT의 값 가져오는 법:
    #        django.conf import settings
    #        settings.MEDIA_ROOT
    # file_path = os.path.join(settings.MEDIA_ROOT, path)

    # 4. file_path를 open한 '파일객체'를
    #    FileResponse에 담아서 리턴
    #       ex) f = open(어딘가, 'rb')
    #           return FileResponse(f, content_type='image/jpeg')
    # return FileResponse(open(file_path, 'rb'), content_type='image/jpeg')

app/members/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from members.forms import LoginForm, SignupForm


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            # 인증 성공시
            login(request,user)
            return redirect('posts:post-list')
        else:
            # 인증 실패시
            pass

    else:
        form = LoginForm()
        context = {
            'form': form,
        }
        return render(request, 'members/login.html', context)


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('posts:post-list')


def signup_view(request):
    context = {
        'form': SignupForm(),
    }
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if User.objects.filter(username=username).exists():
            context['error'] = f'사용자명({username})은 이미 사용중입니다.'
        elif password1 != password2:
            context['error'] = '비밀번호와 비밀번호 확인란의값이 일치하지 않습니다.'
        else:

            # create_user메서드는 create와 달리 자동으로 password해싱을 해줌
            user = User.objects.create_user(
                username = username,
                password = password1,
            )
            login(request, user)
            return redirect('posts:post-list')

        return render(request, 'members/signup.html', context)

app/posts/views.py
from django.shortcuts import render, redirect

# Create your views here.

from posts.forms import PostCreateForm
from .models import Post


def post_list(request):
    posts = Post.objects.all()
    context = {
        'posts': posts,
    }
    return render(request, 'posts/post_list.html', context)


def post_create(request):
    if not request.user.is_authenticated:
        return redirect('posts:post-list')
    
    if request.method == 'POST':
        post = Post(

            photo=request.FILES['photo'],
        )
        post.save()
        return redirect('posts:post-list')
    else:
        form = PostCreateForm()
        context = {
            'form': form,
        }

        return render(request, 'posts/post_create.html', context)

app/templates/base.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Normalize.css: 브라우저마다 다른 CSS기본 설정값들을 같게 맞춰줌 -->
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<title>Instagram</title>
</head>
<body>
	<div id="wrap">
		<!--네비게이션 바-->
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<!--좌측 제목-->
			<a href="#" class="navbar-brand">Instagram</a>
			<!--검색 form-->
			<form action="#" class="form-inline ml-md-auto">
				<input type="text" class="form-control" placeholder="검색">
			</form>
			<!--우측 3개 메뉴 버튼-->
			<ul class="navbar-nav ml-md-auto">
				<li class="nav-item mr-sm-1">
					<a href="{% url 'posts:post-create' %}" class="btn btn-outline-primary">+ Add Post</a>
				</li>
				<li class="nav-item mr-sm-1">
					<a href="#" class="btn btn-outline-secondary">Explore</a>
				</li>
				<li class="nav-item mr-sm-1">
					<a href="#" class="btn btn-outline-secondary">Favorites</a>
				</li>
				<li class="nav-item">
					<a href="#" class="btn btn-outline-secondary">Profile</a>
				</li>
                <li class="nav-item">
					<a href="#" class="btn btn-outline-secondary">
                        Profile
{#                    로그인 한 경우에만 username표시#}
                    {% if user.is_authenticated %}
                        ({{ user.username }})
                    {% endif %}
                    </a>
				</li>
{#            로그인 되었으면 로그아웃버튼, 아니면 로그인/회원가입 버튼 표시#}
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form action="{% url 'members:logout' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-secondary">Logout</button>
                    </form>
				</li>
                {% else %}
                <li class="nav-item mr-sm-1">
				    <a href="{% url 'members:login' %}" class="btn btn-outline-secondary">Login</a>
				</li>
                <li class="nav-item">
					<a href="{% url 'members:signup' %}" class="btn btn-outline-secondary">Signup</a>
				</li>
                {% endif %}
			</ul>

		</nav>

		<div class="container-fluid mt-3">
			{% block content %}
			{% endblock %}
		</div>
	</div>
</body>
</html>

app/templates/members/login.html
{% extends 'base.html' %}

{% block content %}
<div class="col col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
    <h2 class="text-center">로그인</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
            {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="col col-lg-4 offset-lg-4 col-md-6 offset-md-3 col-sm-8 offset-sm-2">
    <h2 class="text-center">회원가입</h2>
    {{ error }}
    <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
            {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
</div>
{% endblock %}

app/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2>포스트 추가</h2>
    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
        </div>
        {% endfor %}
        <button class="btn btn-primary btn-block">업로드</button>
    </form>
</div>
{% endblock %}

<div class="form-group">
            <label for="id-photo">사진 첨부</label>
            <input type="file" id="id-photo" class="form-control-file" name="photo">
        </div>

app/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
<div>
	{% for post in posts %}
	<!--이 div가 lg(width >= 992px)일 때, 4/12의 크기를 가지며 4/12 위치를 기준으로 시작함-->
	<div class="col col-lg-4 offset-lg-4 mb-4">
		<!--Card모양에 대해 미리 정의된 클래스-->
		<div class="card">
			<!--작성자 정보를 나타낼 header부분-->
			<div class="card-header">
				{{ post.author }}
			</div>
			<!--Card의 본문 부분-->
			<div class="card-body">
				<img src="{{ post.photo.url }}" class="card-img-top">
			</div>
		</div>
	</div>
	{% endfor %}

</div>
{% endblock %}